name: B - Terraform Apply

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform apply"
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Terraform init
      run: |
        terraform init -input=false \
          -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME}}"

    - name: Terraform validation
      run: terraform validate

    - name: Terraform apply
      run: terraform apply -auto-approve -input=false -var "pub_key_data=${{ secrets.ID_RSA_WEBODM}}"

    - name: Terraform output
      run: terraform output
