name: B - Terraform Apply

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform apply"
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      id: init
      run: |
        terraform init \
          -input=false -no-color \
          -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME}}"

    - name: Terraform validation
      id: validate
      run: terraform validate

    - name: Terraform apply
      id: apply
      run: |
        terraform apply \
          -auto-approve -input=false -no-color \
          -var "pub_key_data=${{ secrets.ID_RSA_WEBODM}}" \
          -var "fuse_accountname=${{secrets.FUSE_ACCOUNTNAME}}" \
          -var "fuse_accountkey=${{secrets.FUSE_ACCOUNTKEY}}" \
          -var "rclone_azblob_account=${{secrets.RCLONE_AZBLOB_ACCOUNT}}" \
          -var "rclone_azblob_key=${{secrets.RCLONE_AZBLOB_KEH}}" \
          -var "rclone_gdrive_client_id=${{secrets.RCLONE_GDRIVE_CLIENT_ID}}" \
          -var "rclone_gdrive_client_secret=${{secrets.RCLONE_GDRIVE_CLIENT_SECRET}}" \
          -var "rclone_gdrive_token=${{secrets.RCLONE_GDRIVE_TOKEN}}" 

    - name: Terraform output
      id: output
      run: terraform output
