name: Show Me the S3cr3tz
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      run: |
        echo $ARM_CLIENT_ID | sed 's/./& /g'
        echo $ARM_CLIENT_SECRET | sed 's/./& /g'
        echo $ARM_SUBSCRIPTION_ID | sed 's/./& /g'
        echo $ARM_TENET_ID | sed 's/./& /g'
